### ISSUE TITLE
Figure out inputs / outputs for widgets

### ISSUE THREAD

**Issue by Nedomas** [cascade-mcu/cascade-frontend#3]
Sliders, turn off / on

**Comment by vardasss** [comment]
**Controls**
- ON/OFF
- DIMER
**SENSORS**
1. BMP 280
     -Temperature
     - Pressiure
     - Humidity
 2. Temt 6000
     - Ambiant light measurements
 3. SEN0193
     - soil and moister measurements  
**SENSOR OUTPUT**
1. Humidity
  - Show % last reading of humidity.
  - Show last, week, month, .., measurements in diagram
  - Send notification about to high % of humidity
2.AIR PRESSIURE
  - Show last reading of P
  - Show last, week, month, ..., Pressure per hour in diagram
3. AMBIANT light 
  - Show last reading of Ambiant light
  - Show last, day, week, month, ..., measurements in diagram.
  - Send notification about to high or to low light.
4.TEMPERATURE
  - Show last reading of Temperature
  - Show last, day, week, month, ..., Temperature in diagram
5.SEN0193
  - Show last reading of soil and moister measurements
  - Show last, day, week, month, ..., measurements 
  - Send notification if to high water or to low water

**Comment by Nedomas** [comment]
Yeyeye! 💃 thanks @vardasss !
